joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 70  
  
arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
     - j2n6a300_joint_1
     - j2n6a300_joint_2
     - j2n6a300_joint_3
     - j2n6a300_joint_4
     - j2n6a300_joint_5
     - j2n6a300_joint_6

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    j2n6a300_joint_1: {trajectory: 0.1, goal: 0.01}
    j2n6a300_joint_2: {trajectory: 0.1, goal: 0.01}
    j2n6a300_joint_3: {trajectory: 0.1, goal: 0.01}
    j2n6a300_joint_4: {trajectory: 0.1, goal: 0.01}
    j2n6a300_joint_5: {trajectory: 0.1, goal: 0.01}
    j2n6a300_joint_6: {trajectory: 0.1, goal: 0.01}

    
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

  
hand_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
     - j2n6a300_joint_finger_1
     - j2n6a300_joint_finger_2
     - j2n6a300_joint_finger_3

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    j2n6a300_joint_finger_1: {trajectory: 0.1, goal: 0.1}
    j2n6a300_joint_finger_2: {trajectory: 0.1, goal: 0.1}
    j2n6a300_joint_finger_3: {trajectory: 0.1, goal: 0.1}
        
  gains: # Required because we're controlling an effort interface
    j2n6a300_joint_finger_1: {p: 1500,  d: 5, i: 0, i_clamp: 0.1}
    j2n6a300_joint_finger_2: {p: 1500,  d: 5, i: 0, i_clamp: 0.1}
    j2n6a300_joint_finger_3: {p: 1500,  d: 5, i: 0, i_clamp: 0.1}

    
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
