control_configurations:

  - name: "watch"
    components: 
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "js_pub"
        
  - name: "thor"
    components:
      - description: ""
        hardware_interface: "planner_hi"
        controller        : "ur10_thor_prefilter_planner"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "js_pub"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt6_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt5_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt4_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt3_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt2_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt1_1"

planner_hi:
  type: "itia/control/TopicHwIfaceNodelet"
  joint_names: 
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint
  allowed_controller_types: 
  - "controller_type1"  
  feedback_joint_state_topic: "/joint_states"
  command_joint_state_topic: "/joint_pos_target"
  sampling_period: 0.008
  diagnostic_period: 0.1
  feedback_joint_state_timeout: 60

  remap_source_args:
  - "/planner_hi/ur10_thor_prefilter_planner/follow_joint_trajectory/cancel"
  - "/planner_hi/ur10_thor_prefilter_planner/follow_joint_trajectory/feedback"
  - "/planner_hi/ur10_thor_prefilter_planner/follow_joint_trajectory/goal"
  - "/planner_hi/ur10_thor_prefilter_planner/follow_joint_trajectory/result"
  - "/planner_hi/ur10_thor_prefilter_planner/follow_joint_trajectory/status"
  remap_target_args: 
  - "/follow_joint_trajectory/cancel"
  - "/follow_joint_trajectory/feedback"
  - "/follow_joint_trajectory/goal"
  - "/follow_joint_trajectory/result"
  - "/follow_joint_trajectory/status"
  
  ur10_thor_prefilter_planner:
    type: "thor/PrefilterPosVelEffController"
    controlled_joint:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    spline_order: 1
  
ur_hi:
  type: "itia/control/UrHwIfaceNodelet"
  joint_names: 
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint
  allowed_controller_types: 
  - "controller_type1"  
  diagnostic_period: 0.1
  max_velocity: 2
  max_acceleration: 10
  acceleration_coeff: 2.0
  m_driveip_address: "192.168.254.31"
  sampling_period: 0.008
  max_payload: 10
  servo_gain: 2000
  servo_lookahead: 0.03
  speedj_timeout: 0.016
  
  curr2torque: [14.87, 13.26, 11.13, 10.62, 11.03, 11.47]
  
  remap_source_args:
  - "/ur_hi/js_pub/joint_states"
  remap_target_args: 
  - "/joint_states"
  
  js_pub:
    type: ros/control/JointStatePublisher
    controlled_joint:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

  #- name: "joint_teleop_cfg"
    #components:
      #- description: ""
        #hardware_interface: "robot_teleop_hi"
        #controller        : "joint_teleop_ctrl"
      #- description: ""
        #hardware_interface: "ur_hi"
        #controller        : "js_pub"
      #- description: ""
        #hardware_interface: "ur_hi"
        #controller        : "linkpos_to_vel_jnt6_1"
      #- description: ""
        #hardware_interface: "ur_hi"
        #controller        : "linkpos_to_vel_jnt5_1"
      #- description: ""
        #hardware_interface: "ur_hi"
        #controller        : "linkpos_to_vel_jnt4_1"
      #- description: ""
        #hardware_interface: "ur_hi"
        #controller        : "linkpos_to_vel_jnt3_1"
      #- description: ""
        #hardware_interface: "ur_hi"
        #controller        : "linkpos_to_vel_jnt2_1"
      #- description: ""
        #hardware_interface: "ur_hi"
        #controller        : "linkpos_to_vel_jnt1_1"
        
#robot_teleop_hi:
  #type: "itia/control/TopicHwIfaceNodelet"
  #joint_names:
    #- shoulder_pan_joint
    #- shoulder_lift_joint
    #- elbow_joint
    #- wrist_1_joint
    #- wrist_2_joint
    #- wrist_3_joint

  #feedback_joint_state_topic: "/joint_states"
  #command_joint_state_topic: "/joint_pos_target"
  #sampling_period: 0.008
  #diagnostic_period: 0.1
  #feedback_joint_state_timeout: 20
  
  #joint_teleop_ctrl:
    #type: "itia/control/JointTeleopController"
    #setpoint_topic_name: "/target_joint_state"
    #controlled_joints:
      #- shoulder_pan_joint
      #- shoulder_lift_joint
      #- elbow_joint
      #- wrist_1_joint
      #- wrist_2_joint
      #- wrist_3_joint




