control_configurations:
  - name: "ss"
    components: 
      - description: ""
        hardware_interface: "planner_hi"
        controller        : "fir_planner"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "js_pub"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt6_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt5_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt4_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt3_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt2_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt1_1"

  - name: "speedj"
    components: 
      - description: ""
        hardware_interface: "planner_hi"
        controller        : "fir_planner"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "js_pub"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt6_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt5_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt4_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt3_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt2_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt1_1"

  - name: "thor"
    components: 
      - description: ""
        hardware_interface: "planner_hi"
        controller        : "thor_planner"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "js_pub"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt6_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt5_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt4_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt3_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt2_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt1_1"

  - name: "impedance"
    components:
      - description: ""
        hardware_interface: "planner_Joint_impedance_hi"
        controller        : "thor_planner"
      - description: ""
        hardware_interface: "joint_impedance_hi"
        controller        : "joint_impedance_ctrl"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "js_pub"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt6_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt5_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt4_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt3_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt2_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt1_1"
  
  - name: "servoj"
    components: 
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "js_pub"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "fir_planner"

        
  - name: "onlyctrl"
    components: 
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "js_pub"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt6_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt5_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt4_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt3_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt2_1"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "linkpos_to_vel_jnt1_1"

  - name: "watch"
    components: 
      - description: ""
        hardware_interface: "planner_hi"
        controller        : "NONE"
      - description: ""
        hardware_interface: "ur_hi"
        controller        : "js_pub"

      
planner_hi:
  type: "itia/control/TopicHwIfaceNodelet"
  joint_names: 
  - ur10_shoulder_pan_joint
  - ur10_shoulder_lift_joint
  - ur10_elbow_joint
  - ur10_wrist_1_joint
  - ur10_wrist_2_joint
  - ur10_wrist_3_joint
  allowed_controller_types: 
  - "controller_type1"  
  feedback_joint_state_topic: "/joint_states"
  command_joint_state_topic: "/joint_impedance_pos_target"
  sampling_period: 0.008
  diagnostic_period: 0.1
  feedback_joint_state_timeout: 20

  remap_source_args:
  - "/planner_hi/fir_planner/follow_joint_trajectory/cancel"
  - "/planner_hi/fir_planner/follow_joint_trajectory/feedback"
  - "/planner_hi/fir_planner/follow_joint_trajectory/goal"
  - "/planner_hi/fir_planner/follow_joint_trajectory/result"
  - "/planner_hi/fir_planner/follow_joint_trajectory/status"
  remap_target_args:
  - "/ur10/follow_joint_trajectory/cancel"
  - "/ur10/follow_joint_trajectory/feedback"
  - "/ur10/follow_joint_trajectory/goal"
  - "/ur10/follow_joint_trajectory/result"
  - "/ur10/follow_joint_trajectory/status"

  fir_planner:
    type: "itia/motion/FirController"
    controlled_joint:
    - ur10_shoulder_pan_joint
    - ur10_shoulder_lift_joint
    - ur10_elbow_joint
    - ur10_wrist_1_joint
    - ur10_wrist_2_joint
    - ur10_wrist_3_joint

    fir_params:
      sample_period: 0.008
      cruise_jnt_vel: [1.8, 1.8, 2.8, 2.8, 2.8, 2.8]
      acc_vel_ratio: 2.0   # acc/vel
      default_path_accuracy: 0.1
      default_goal_accuracy: 0
      np: 2
      stop_when_zero_override: true


planner_joint_impedance_hi:
  type: "itia/control/TopicHwIfaceNodelet"
  joint_names:
  - ur10_shoulder_pan_joint
  - ur10_shoulder_lift_joint
  - ur10_elbow_joint
  - ur10_wrist_1_joint
  - ur10_wrist_2_joint
  - ur10_wrist_3_joint
  allowed_controller_types:
  - "controller_type1"
  feedback_joint_state_topic: "/joint_states"
  command_joint_state_topic: "/joint_impedance_pos_target"
  sampling_period: 0.008
  diagnostic_period: 0.1
  feedback_joint_state_timeout: 20

  thor:
    type: "thor/PrefilterPosVelEffController"
    controlled_joint:
    - ur10_shoulder_pan_joint
    - ur10_shoulder_lift_joint
    - ur10_elbow_joint
    - ur10_wrist_1_joint
    - ur10_wrist_2_joint
    - ur10_wrist_3_joint
    spline_order: 2



joint_impedance_hi:
  type: "itia/control/TopicHwIfaceNodelet"
  joint_names:
  - ur10_shoulder_pan_joint
  - ur10_shoulder_lift_joint
  - ur10_elbow_joint
  - ur10_wrist_1_joint
  - ur10_wrist_2_joint
  - ur10_wrist_3_joint
  allowed_controller_types:
  - "controller_type1"
  feedback_joint_state_topic: "/joint_states"
  command_joint_state_topic: "/joint_pos_target"
  sampling_period: 0.008
  diagnostic_period: 0.1
  feedback_joint_state_timeout: 20

  joint_impedance_ctrl:
    type: "itia/control/JointImpedanceController"
    inertia: [1,1,1,1,1,1]
    stiffness: [1,1,1,1,1,1]
    damping: [1,1,1,1,1,1]
    torque_deadband: [0,0,0,0,0,0]
    joint_target_topic: "/joint_impedance_pos_target"
    external_torques_topic: "external_torques"
  
  
ur_hi:
  type: "itia/control/UrHwIfaceNodelet"
  joint_names: 
  - ur10_shoulder_pan_joint
  - ur10_shoulder_lift_joint
  - ur10_elbow_joint
  - ur10_wrist_1_joint
  - ur10_wrist_2_joint
  - ur10_wrist_3_joint
  allowed_controller_types: 
  - "controller_type1"  
  diagnostic_period: 0.1
  max_velocity: 2
  max_acceleration: 10
  acceleration_coeff: 2.0
  m_driveip_address: "192.168.254.33"
  sampling_period: 0.008
  max_payload: 10
  servo_gain: 2000
  servo_lookahead: 0.03
  speedj_timeout: 0.016
  
  curr2torque: [14.87, 13.26, 11.13, 10.62, 11.03, 11.47]

  remap_source_args:
  - "/ur_hi/joint_states"
  - "/ur_hi/fir_planner/follow_joint_trajectory/cancel"
  - "/ur_hi/fir_planner/follow_joint_trajectory/feedback"
  - "/ur_hi/fir_planner/follow_joint_trajectory/goal"
  - "/ur_hi/fir_planner/follow_joint_trajectory/result"
  - "/ur_hi/fir_planner/follow_joint_trajectory/status"
  remap_target_args: 
  - "/ur10/joint_states"
  - "/ur10/follow_joint_trajectory/cancel"
  - "/ur10/follow_joint_trajectory/feedback"
  - "/ur10/follow_joint_trajectory/goal"
  - "/ur10/follow_joint_trajectory/result"
  - "/ur10/follow_joint_trajectory/status"
  
  js_pub:
    type:         joint_state_controller/JointStateController
    publish_rate: 125

  fir_planner:
    type: "itia/motion/FirController"
    controlled_joint:
    - ur5_shoulder_pan_joint
    - ur5_shoulder_lift_joint
    - ur5_elbow_joint
    - ur5_wrist_1_joint
    - ur5_wrist_2_joint
    - ur5_wrist_3_joint
    
    fir_params:
      sample_period: 0.008
      cruise_jnt_vel: [1.8, 1.8, 2.8, 2.8, 2.8, 2.8]
      acc_vel_ratio: 0.2   # acc/vel
      default_path_accuracy: 0.1
      default_goal_accuracy: 0
      np: 2  
      stop_when_zero_override: true

      
      
zeros:
  shoulder_pan_joint: 0
  shoulder_lift_joint: -1.5708
  elbow_joint: 1.5708
  wrist_1_joint: 0
  wrist_2_joint: 0
  wrist_3_joint: 0
